//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SBIRSystem.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_SBIRSYSTEM_FORM             101
#define IDR_MAINFRAME                   128
#define IDR_SBIRSYTYPE                  129
#define IDD_IMAGEBASE                   130
#define IDD_DIALOG_PARAMENTS            131
#define IDD_DIALOG_LOADSAMPLE           133
#define IDD_DIALOG_DISPLAYRESULT        134
#define IDC_SAMPLEIMAGE_BOX             1000
#define IDC_SAMPLEIMAGE_PICTURE         1001
#define IDC_CONTROL_BOX                 1002
#define IDC_BUTTON_OPENSAMPLE           1003
#define IDC_BUTTON_IMAGEDATABASE        1004
#define IDC_BUTTON_RETRIEVAL            1005
#define IDC_BUTTON_RELEVANCEFEEDBACK    1006
#define IDC_INOFORMATION_BOX            1007
#define IDC_BUTTON_PARAMETER            1008
#define IDC_STATIC_IMAGEDATABASESIZE    1010
#define IDC_THRESHOLD                   1011
#define IDC_STATIC_THRESHOLD            1012
#define IDC_STATIC_IMAGEPATH            1013
#define IDC_STATIC_CURRENT_STATE        1014
#define IDC_DATA_IMAGEDATABASESIZE      1015
#define IDC_DATA_IMAGERETRIEVALTIME     1016
#define IDC_DATA_SAMPLEID               1017
#define IDC_RETRIEVELRESULT_BOX         1018
#define IDC_DATA_SIMILARITY             1021
#define IDC_STATIC_RESULTNUMBER         1022
#define IDC_DATA_RESULTNUMBER           1023
#define IDC_DATA_SIMILARITY2            1024
#define IDC_DATA_SIMILARITY3            1025
#define IDC_DATA_SIMILARITY4            1026
#define IDC_DATA_SIMILARITY5            1027
#define IDC_RESULTE1                    1028
#define IDC_RESULTE2                    1029
#define IDC_RESULTE3                    1030
#define IDC_RESULT_INFORMATION          1031
#define IDC_BUTTON_NEXTPAGE             1032
#define IDC_BUTTON_PREPAGE              1033
#define IDC_BUTTON_HOMEPAGE             1034
#define IDC_RESULTE4                    1035
#define IDC_RESULTE5                    1036
#define IDC_RADIO1                      1037
#define IDC_RADIO2                      1038
#define IDC_RADIO3                      1039
#define IDC_RADIO4                      1040
#define IDC_BUTTON_LOAD                 1040
#define IDC_RADIO5                      1041
#define IDC_BUTTON_CREAT                1041
#define IDC_RADIO6                      1042
#define IDC_RADIO7                      1043
#define IDC_RADIO8                      1044
#define IDC_RADIO9                      1045
#define IDC_RADIO10                     1046
#define IDC_RADIO11                     1047
#define IDC_RADIO12                     1048
#define IDC_RADIO13                     1049
#define IDC_RADIO14                     1050
#define IDC_RADIO15                     1051
#define IDC_RESULTE6                    1052
#define IDC_DATA_SIMILARITY6            1053
#define IDC_RADIO16                     1054
#define IDC_RADIO17                     1055
#define IDC_RADIO18                     1056
#define IDC_RESULTE7                    1057
#define IDC_DATA_SIMILARITY7            1058
#define IDC_RADIO19                     1059
#define IDC_RADIO20                     1060
#define IDC_RADIO21                     1061
#define IDC_RESULTE8                    1062
#define IDC_DATA_SIMILARITY8            1063
#define IDC_RADIO22                     1064
#define IDC_RADIO23                     1065
#define IDC_RADIO24                     1066
#define IDC_RESULTE9                    1067
#define IDC_DATA_SIMILARITY9            1068
#define IDC_RADIO25                     1069
#define IDC_RADIO26                     1070
#define IDC_RADIO27                     1071
#define IDC_RESULTE10                   1072
#define IDC_DATA_SIMILARITY10           1073
#define IDC_RADIO28                     1074
#define IDC_RADIO29                     1075
#define IDC_RADIO30                     1076
#define IDC_RESULTE11                   1077
#define IDC_DATA_SIMILARITY11           1078
#define IDC_RADIO31                     1079
#define IDC_RADIO32                     1080
#define IDC_RADIO33                     1081
#define IDC_RESULTE12                   1082
#define IDC_DATA_SIMILARITY12           1083
#define IDC_RADIO34                     1084
#define IDC_RADIO35                     1085
#define IDC_RADIO36                     1086
#define IDC_STATIC_RESULTNUMBER2        1087
#define IDC_DATA_STUDY_TIMES            1088
#define IDC_DATA_TOTALPAGES             1089
#define IDC_EDIT1                       1089
#define IDC_STATIC_RESULTNUMBER3        1090
#define IDC_EDIT2                       1090
#define IDC_DATA_CURRENTPAGE            1091
#define IDC_EDIT3                       1091
#define IDC_CHECK1                      1092
#define IDC_DATA_FEEDBACKTIME           1092
#define IDC_PATH                        1095
#define IDC_RECALL                      1096
#define IDC_PRECISE                     1097
#define IDC_LIST_ANNOTION               1098
#define IDC_BUTTON_DISPLAY_CUURETN      1099
#define IDC_LIST_KEYWORDRETRIEVIED      1099
#define IDC_BUTTON_NEXT                 1100
#define IDC_BROWSEIMAGE                 1101
#define IDC_RESULTIMAGE_ORGINAL         1102
#define IDC_STATIC_WIDTH                1104
#define IDC_STATIC_HEIGHT               1105
#define IDC_BUTTON_SAVE                 1106
#define IDC_BUTTON_RETRIEVAL_CHANGE     1107
#define IDC_EDIT_KEYWORD_RETRIEVIED     1109
#define IDC_BUTTON_KEYWORDRETRIEVAL     1110
#define IDC_GETINFORMATINO              32771
#define IDC_RETRIEVAL_METHOD_TEST       32772
#define IDC_INITIAL_SEMANTICANNOTION    32773
#define ID_OPEN_ANNOTION                32774
#define ID_CLOSE_ANNOTION               32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1116
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
